// Demo data used when Supabase is not connected

export const demoProfile = {
  id: 'demo-user-001',
  full_name: 'Priya Sharma',
  avatar_url: null,
  status_type: 'international_student' as const,
  university: 'University of Ottawa',
  program: 'Computer Science',
  arrival_date: '2025-09-15',
  city: 'Ottawa',
  province: 'Ontario',
  country_of_origin: 'India',
  languages: ['English', 'Hindi'],
  sin_obtained: true,
  ohip_status: 'applied',
  study_permit_expiry: '2027-08-31',
  preferred_language: 'en',
  onboarding_complete: true,
  email_notifications: true,
  created_at: '2025-09-15T12:00:00Z',
  updated_at: '2025-09-15T12:00:00Z',
}

export const demoForumPosts = [
  {
    id: 'fp-1',
    user_id: 'demo-user-001',
    title: 'How long does it take to get a SIN?',
    content: 'I just arrived in Ottawa and need to apply for my SIN. How long does the process take? Can I go to any Service Canada office?',
    category: 'immigration',
    tags: ['SIN', 'newcomer', 'documents'],
    city: 'Ottawa',
    upvotes: 12,
    reply_count: 5,
    pinned: false,
    language: 'en',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    profiles: { full_name: 'Ahmed Hassan', avatar_url: null },
  },
  {
    id: 'fp-2',
    user_id: 'demo-user-002',
    title: 'Best bank account for international students?',
    content: 'I am comparing TD, Scotiabank, and RBC. Which one has the best newcomer package? Any recommendations?',
    category: 'banking',
    tags: ['banking', 'student', 'newcomer'],
    city: 'Ottawa',
    upvotes: 8,
    reply_count: 7,
    pinned: false,
    language: 'en',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    profiles: { full_name: 'Wei Chen', avatar_url: null },
  },
  {
    id: 'fp-3',
    user_id: 'demo-user-003',
    title: 'Where to find halal food near uOttawa?',
    content: 'Just moved here and looking for halal grocery stores and restaurants near the university campus. Any suggestions?',
    category: 'community',
    tags: ['food', 'halal', 'Ottawa'],
    city: 'Ottawa',
    upvotes: 15,
    reply_count: 9,
    pinned: false,
    language: 'en',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    profiles: { full_name: 'Fatima Al-Rashidi', avatar_url: null },
  },
]

export const demoJobs = [
  {
    id: 'job-1',
    posted_by: null,
    title: 'Library Student Assistant',
    company: 'Carleton University Library',
    description: 'Assist with library operations including shelving, circulation desk duties, and helping students find resources.',
    requirements: 'Must be enrolled as a full-time student. Previous library experience an asset.',
    job_type: 'on_campus' as const,
    salary_range: '$16.55/hr',
    location: 'Carleton University',
    city: 'Ottawa',
    remote: false,
    status_types: ['international_student', 'permanent_resident'],
    languages_needed: ['English'],
    application_url: 'https://carleton.ca/careers',
    contact_email: null,
    deadline: '2026-04-15',
    is_active: true,
    views: 45,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'job-2',
    posted_by: null,
    title: 'Junior Software Developer (Co-op)',
    company: 'Shopify',
    description: 'Join our engineering team for a 4-month co-op term. Work on real projects that impact millions of merchants worldwide.',
    requirements: 'Enrolled in CS or related program. Familiar with Ruby, JavaScript, or React.',
    job_type: 'co_op' as const,
    salary_range: '$25-30/hr',
    location: 'Ottawa / Remote',
    city: 'Ottawa',
    remote: true,
    status_types: ['international_student', 'permanent_resident'],
    languages_needed: ['English'],
    application_url: 'https://shopify.com/careers',
    contact_email: null,
    deadline: '2026-05-01',
    is_active: true,
    views: 120,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'job-3',
    posted_by: null,
    title: 'Research Assistant — AI Lab',
    company: 'University of Ottawa',
    description: 'Assist with NLP research projects. Responsibilities include data collection, model training, and writing documentation.',
    requirements: 'Graduate student in CS or Linguistics. Experience with Python and machine learning.',
    job_type: 'on_campus' as const,
    salary_range: '$22/hr',
    location: 'SITE Building, uOttawa',
    city: 'Ottawa',
    remote: false,
    status_types: ['international_student', 'permanent_resident'],
    languages_needed: ['English'],
    application_url: null,
    contact_email: 'ailab@uottawa.ca',
    deadline: '2026-04-30',
    is_active: true,
    views: 67,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'job-4',
    posted_by: null,
    title: 'Barista / Cashier',
    company: 'Tim Hortons — Rideau Centre',
    description: 'Part-time position. Flexible hours perfect for students.',
    requirements: 'No experience needed. Training provided.',
    job_type: 'part_time' as const,
    salary_range: '$16.55/hr + tips',
    location: 'Rideau Centre',
    city: 'Ottawa',
    remote: false,
    status_types: ['international_student', 'permanent_resident', 'refugee'],
    languages_needed: ['English'],
    application_url: null,
    contact_email: null,
    deadline: null,
    is_active: true,
    views: 89,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
]

export const demoHousing = [
  {
    id: 'h-1',
    user_id: 'demo-user-010',
    title: 'Furnished Room near uOttawa — All Inclusive',
    description: 'Bright furnished room in a 3-bedroom apartment. 5 min walk to campus. Laundry in building. Quiet neighbourhood.',
    listing_type: 'room' as const,
    price_monthly: 750,
    bedrooms: 1,
    bathrooms: 1,
    address: 'Henderson Ave, Sandy Hill',
    city: 'Ottawa',
    latitude: 45.4231,
    longitude: -75.6831,
    available_from: '2026-05-01',
    furnished: true,
    utilities: true,
    pets_allowed: false,
    gender_pref: null,
    student_only: true,
    images: [],
    amenities: ['WiFi', 'Laundry', 'Kitchen'],
    languages: ['English', 'French'],
    is_active: true,
    views: 34,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'h-2',
    user_id: 'demo-user-011',
    title: '1BR Apartment — Centretown, Close to OC Transpo',
    description: 'Spacious 1-bedroom apartment near Centretown. Walk to Parliament, Rideau. On major bus routes.',
    listing_type: 'apartment' as const,
    price_monthly: 1400,
    bedrooms: 1,
    bathrooms: 1,
    address: 'Bank Street, Centretown',
    city: 'Ottawa',
    latitude: 45.4112,
    longitude: -75.6981,
    available_from: '2026-04-01',
    furnished: false,
    utilities: false,
    pets_allowed: true,
    gender_pref: null,
    student_only: false,
    images: [],
    amenities: ['Parking', 'Gym', 'Balcony'],
    languages: ['English'],
    is_active: true,
    views: 56,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

export const demoNotifications = [
  {
    id: 'n-1',
    user_id: 'demo-user-001',
    type: 'forum_reply',
    title: 'New reply to your post',
    body: 'Ahmed replied to "How long does it take to get a SIN?"',
    read: false,
    action_url: '/forum/fp-1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'n-2',
    user_id: 'demo-user-001',
    type: 'reminder',
    title: 'OHIP eligibility coming up',
    body: 'You may be eligible for OHIP soon. Check your roadmap for next steps.',
    read: false,
    action_url: '/roadmap',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'n-3',
    user_id: 'demo-user-001',
    type: 'welcome',
    title: 'Welcome to MaplePath!',
    body: 'Start your settlement journey by completing your roadmap.',
    read: true,
    action_url: '/',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
]

export const demoMapPins = [
  {
    id: 'pin-1', user_id: null, title: 'Ottawa Mosque', category: 'worship',
    description: 'Friday prayers, Islamic library, community events.',
    address: '251 Northwestern Ave', latitude: 45.4025, longitude: -75.7195,
    city: 'Ottawa', languages: ['English', 'Arabic'], website: 'https://ottawamosque.ca',
    phone: '613-722-8763', hours: 'Daily 5am-10pm', verified: true, upvotes: 22, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-2', user_id: null, title: 'Hindu Temple of Ottawa-Carleton', category: 'worship',
    description: 'Temple services, cultural events, vegetarian food.',
    address: '4835 Bank St', latitude: 45.3385, longitude: -75.6361,
    city: 'Ottawa', languages: ['English', 'Hindi'], website: null,
    phone: '613-822-2210', hours: 'Daily 9am-8pm', verified: true, upvotes: 18, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-3', user_id: null, title: 'Shawarma Palace', category: 'food',
    description: 'Best shawarma in Ottawa. Halal certified.',
    address: '464 Rideau St', latitude: 45.4310, longitude: -75.6820,
    city: 'Ottawa', languages: ['English', 'Arabic'], website: null,
    phone: '613-789-4747', hours: 'Mon-Sun 11am-12am', verified: true, upvotes: 45, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-4', user_id: null, title: 'TD Bank — Rideau Branch', category: 'banking',
    description: 'Newcomer banking packages available. Multilingual staff.',
    address: '170 Rideau St', latitude: 45.4284, longitude: -75.6893,
    city: 'Ottawa', languages: ['English', 'French', 'Mandarin'], website: 'https://td.com',
    phone: '613-783-6510', hours: 'Mon-Fri 9am-6pm', verified: true, upvotes: 10, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-5', user_id: null, title: 'Appletree Medical Clinic', category: 'health',
    description: 'Walk-in clinic. No OHIP required (fee applies).',
    address: '363 Coventry Rd', latitude: 45.4085, longitude: -75.6645,
    city: 'Ottawa', languages: ['English', 'French'], website: 'https://appletreemedical.ca',
    phone: '613-727-4723', hours: 'Mon-Fri 8am-8pm, Sat-Sun 9am-3pm', verified: true, upvotes: 14, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-6', user_id: null, title: 'uOttawa International Office', category: 'education',
    description: 'Support for international students — immigration, academic advising, and more.',
    address: '75 Laurier Ave E', latitude: 45.4235, longitude: -75.6830,
    city: 'Ottawa', languages: ['English', 'French'], website: 'https://uottawa.ca/international',
    phone: '613-562-5847', hours: 'Mon-Fri 8:30am-4:30pm', verified: true, upvotes: 30, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-7', user_id: null, title: 'Service Canada Centre', category: 'community',
    description: 'Apply for SIN, EI, and other federal services.',
    address: '110 O\'Connor St', latitude: 45.4205, longitude: -75.6950,
    city: 'Ottawa', languages: ['English', 'French'], website: 'https://canada.ca/service-canada',
    phone: '1-800-206-7218', hours: 'Mon-Fri 8:30am-4pm', verified: true, upvotes: 25, image_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pin-8', user_id: null, title: 'Rideau Centre', category: 'recreation',
    description: 'Major shopping mall. Food court, retail, cinema.',
    address: '50 Rideau St', latitude: 45.4260, longitude: -75.6925,
    city: 'Ottawa', languages: ['English', 'French'], website: 'https://rideaucentre.com',
    phone: null, hours: 'Mon-Sat 10am-9pm, Sun 11am-6pm', verified: true, upvotes: 8, image_url: null,
    created_at: new Date().toISOString(),
  },
]

export const demoResources = [
  { id: 'r-1', category: 'Immigration', title: 'IRCC — Immigration, Refugees and Citizenship Canada', description: 'Official government portal for all immigration applications, status checks, and forms.', url: 'https://www.canada.ca/en/immigration-refugees-citizenship.html', phone: '1-888-242-2100', address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-2', category: 'Immigration', title: 'IRCC Web Form', description: 'Submit questions about your immigration application online.', url: 'https://ircc.canada.ca/english/contacts/web-form.asp', phone: null, address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-3', category: 'Banking', title: 'TD New to Canada Banking', description: 'Newcomer banking package with no monthly fee for the first year.', url: 'https://www.td.com/ca/en/personal-banking/solutions/new-to-canada', phone: '1-866-222-3456', address: null, city: 'National', province: 'All', language: ['en', 'fr', 'zh'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-4', category: 'Banking', title: 'RBC Newcomer Advantage', description: 'Free banking for 1 year, credit card with no Canadian credit history needed.', url: 'https://www.rbc.com/newcomers/', phone: null, address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-5', category: 'Health', title: 'OHIP Application', description: 'Apply for Ontario Health Insurance Plan. 3-month waiting period for newcomers.', url: 'https://www.ontario.ca/page/apply-ohip-and-get-health-card', phone: '1-866-532-3161', address: null, city: 'Ontario', province: 'Ontario', language: ['en', 'fr'], status_type: ['international_student', 'permanent_resident', 'refugee'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-6', category: 'Health', title: 'UHIP — University Health Insurance', description: 'Mandatory health insurance for international students during OHIP waiting period.', url: 'https://uhip.ca', phone: null, address: null, city: 'Ontario', province: 'Ontario', language: ['en'], status_type: ['international_student'], free: false, verified: true, created_at: new Date().toISOString() },
  { id: 'r-7', category: 'Housing', title: 'CMHC — Housing Resources', description: 'Canada Mortgage and Housing Corporation — tenant rights and housing information.', url: 'https://www.cmhc-schl.gc.ca/', phone: null, address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-8', category: 'Employment', title: 'Job Bank Canada', description: 'Official government job board with thousands of listings across Canada.', url: 'https://www.jobbank.gc.ca/', phone: null, address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-9', category: 'Education', title: 'LINC — Language Instruction for Newcomers', description: 'Free English and French language classes for permanent residents and refugees.', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/new-life-canada/improve-english-french.html', phone: null, address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['permanent_resident', 'refugee'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-10', category: 'Legal Aid', title: 'Legal Aid Ontario', description: 'Free legal services for low-income residents. Immigration, family, and criminal law.', url: 'https://www.legalaid.on.ca/', phone: '1-800-668-8258', address: null, city: 'Ontario', province: 'Ontario', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-11', category: 'Community', title: 'OCISO — Ottawa Community Immigrant Services', description: 'Settlement services, language training, employment support for newcomers.', url: 'https://ociso.org/', phone: '613-725-0202', address: '959 Wellington St W', city: 'Ottawa', province: 'Ontario', language: ['en', 'fr', 'ar'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-12', category: 'Transport', title: 'OC Transpo — UPass', description: 'Unlimited transit pass for post-secondary students. Included in tuition fees.', url: 'https://www.octranspo.com/en/fares/u-pass/', phone: '613-741-4390', address: null, city: 'Ottawa', province: 'Ontario', language: ['en', 'fr'], status_type: ['international_student'], free: false, verified: true, created_at: new Date().toISOString() },
  { id: 'r-13', category: 'Mental Health', title: 'BounceBack Ontario', description: 'Free guided self-help program for managing low mood, stress, and anxiety.', url: 'https://bouncebackontario.ca/', phone: '1-866-345-0224', address: null, city: 'Ontario', province: 'Ontario', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-14', category: 'Community', title: 'LASI World Skills', description: 'Employment services, mentoring, and skills training for immigrants.', url: 'https://www.lasiworldskills.ca/', phone: '613-233-0453', address: '219 Argyle Ave', city: 'Ottawa', province: 'Ontario', language: ['en', 'fr', 'ar'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
  { id: 'r-15', category: 'Immigration', title: 'Service Canada — SIN Application', description: 'Apply for your Social Insurance Number (SIN) — required for working in Canada.', url: 'https://www.canada.ca/en/employment-social-development/services/sin.html', phone: '1-866-274-6627', address: null, city: 'National', province: 'All', language: ['en', 'fr'], status_type: ['all'], free: true, verified: true, created_at: new Date().toISOString() },
]
