-- ============================================================
-- MaplePath Seed Data
-- Realistic data for Ottawa and major Canadian cities
-- ============================================================

-- ============================================================
-- RESOURCES (60 rows)
-- ============================================================

-- Immigration (10)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'immigration', 'Immigration, Refugees and Citizenship Canada (IRCC)', 'Federal department responsible for immigration, citizenship and refugee programs in Canada.', 'https://www.canada.ca/en/immigration-refugees-citizenship.html', '1-888-242-2100', NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'immigration', 'OCISO - Ottawa Community Immigrant Services Organization', 'Settlement services including language training, employment support, and community connections for newcomers.', 'https://ociso.org', '613-725-0202', '959 Wellington St W', 'Ottawa', 'Ontario', '{en,fr,ar,so}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'LASI World Skills', 'Employment-focused settlement agency providing job search support, language training and skills bridging.', 'https://www.lasiworldskills.ca', '613-232-3322', '219 Argyle Ave Suite 400', 'Ottawa', 'Ontario', '{en,fr,ar}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'Catholic Centre for Immigrants', 'Settlement and integration support including housing help, language classes and social support for refugees and immigrants.', 'https://cciottawa.ca', '613-232-9634', '219 Argyle Ave', 'Ottawa', 'Ontario', '{en,fr,ar}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'COSTI Immigrant Services', 'Multi-service agency providing employment, education, language and settlement services for newcomers in the Toronto area.', 'https://www.costi.org', '416-658-1600', '1710 Dufferin St', 'Toronto', 'Ontario', '{en,it,es,pt,zh}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'MOSAIC', 'One of the largest settlement agencies in BC providing language, employment and community programs.', 'https://www.mosaicbc.org', '604-254-9626', '1720 Grant St', 'Vancouver', 'British Columbia', '{en,zh,ar,fa,ko}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'Immigration Québec', 'Provincial immigration ministry handling Quebec-specific immigration programs and certificates.', 'https://www.quebec.ca/en/immigration', '1-877-644-4545', NULL, 'Montreal', 'Quebec', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'immigration', 'Calgary Immigrant Women''s Association', 'Settlement and integration services focused on immigrant women including employment, language and family support.', 'https://www.ciwa-online.com', '403-263-4414', '200-138 4th Ave SE', 'Calgary', 'Alberta', '{en,ar,fa,zh,es}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'immigration', 'Study Permit - IRCC', 'Official information on applying for, extending and understanding study permit conditions in Canada.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html', '1-888-242-2100', NULL, NULL, NULL, '{en,fr}', '{international_student}', true, true),
(gen_random_uuid(), 'immigration', 'Express Entry - IRCC', 'Federal economic immigration pathway for skilled workers wanting to become permanent residents.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', '1-888-242-2100', NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident}', true, true);

-- Banking (6)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'banking', 'TD New to Canada Banking Package', 'Newcomer banking bundle with no-fee chequing for the first year, credit card with no Canadian credit history required.', 'https://www.td.com/ca/en/personal-banking/solutions/new-to-canada', '1-866-222-3456', NULL, NULL, NULL, '{en,fr,zh,ko,es}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'banking', 'RBC Newcomer Advantage', 'Free day-to-day banking, no-annual-fee credit card and preferential rates for newcomers within 3 years of arrival.', 'https://www.rbc.com/newcomers', '1-800-769-2511', NULL, NULL, NULL, '{en,fr,zh}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'banking', 'Scotiabank StartRight Program', 'Newcomer banking program offering free chequing, a credit card, and international money transfers for newcomers.', 'https://www.scotiabank.com/ca/en/personal/new-to-canada.html', '1-800-472-6842', NULL, NULL, NULL, '{en,fr,zh,es}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'banking', 'BMO NewStart Program', 'Banking package for newcomers including a no-fee chequing account, credit card and financial advice for first year.', 'https://www.bmo.com/en-ca/main/personal/new-to-canada/', '1-877-225-5266', NULL, NULL, NULL, '{en,fr,zh}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'banking', 'CIBC Smart Account for Newcomers', 'Newcomer banking with unlimited transactions, no monthly fee for the first year, and no credit history needed.', 'https://www.cibc.com/en/personal-banking/newcomers-to-canada.html', '1-800-465-2422', NULL, NULL, NULL, '{en,fr,zh}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'banking', 'Canada Revenue Agency - Opening a Bank Account', 'Government guidance on what documents newcomers need to open a bank account in Canada.', 'https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html', NULL, NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true);

-- Health (7)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'health', 'Ontario Health Insurance Plan (OHIP)', 'Provincial health insurance covering doctor visits, hospital stays, and medical tests for eligible Ontario residents.', 'https://www.ontario.ca/page/apply-ohip-and-get-health-card', '1-866-532-3161', NULL, NULL, 'Ontario', '{en,fr}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'health', 'Appletree Medical Group - Ottawa', 'Network of walk-in clinics across Ottawa accepting patients with and without OHIP coverage.', 'https://www.appletreemedicalgroup.com', '613-225-8733', '2211 Riverside Dr', 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', false, true),
(gen_random_uuid(), 'health', 'University of Ottawa Health Services', 'Campus health clinic for uOttawa students offering general medicine, mental health, and immunizations.', 'https://www.uottawa.ca/wellness/health-services', '613-564-3950', '100 Marie Curie, Room 213', 'Ottawa', 'Ontario', '{en,fr}', '{international_student}', true, true),
(gen_random_uuid(), 'health', 'Telehealth Ontario', '24/7 free telephone health advice service staffed by registered nurses available in multiple languages.', 'https://www.ontario.ca/page/get-medical-advice-telehealth-ontario', '1-866-797-0000', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'health', 'Carleton University Health and Counselling Services', 'On-campus clinic for Carleton students offering medical appointments, mental health support and health education.', 'https://carleton.ca/health/', '613-520-6674', '2600 CTTC Building', 'Ottawa', 'Ontario', '{en}', '{international_student}', true, true),
(gen_random_uuid(), 'health', 'UHIP - University Health Insurance Plan', 'Mandatory health insurance plan for international students at Ontario universities during the OHIP waiting period.', 'https://uhip.ca', NULL, NULL, NULL, 'Ontario', '{en}', '{international_student}', false, true),
(gen_random_uuid(), 'health', 'Ottawa Public Health - Newcomer Immunization', 'Free immunization services and catch-up vaccination programs for newly arrived immigrants and refugees.', 'https://www.ottawapublichealth.ca', '613-580-6744', '100 Constellation Dr', 'Ottawa', 'Ontario', '{en,fr,ar,so}', '{permanent_resident,refugee}', true, true);

-- Housing (6)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'housing', 'Ottawa Community Housing Corporation', 'Largest social housing provider in Ottawa offering subsidized rental units for low-income residents and newcomers.', 'https://www.och-lco.ca', '613-564-1064', '39 Auriga Dr', 'Ottawa', 'Ontario', '{en,fr}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'housing', 'Canada Mortgage and Housing Corporation (CMHC)', 'Federal housing agency providing rental market reports, housing information and programs for newcomers.', 'https://www.cmhc-schl.gc.ca', '1-800-668-2642', NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'housing', 'Places4Students', 'Student-focused housing listing platform with verified landlords near Canadian colleges and universities.', 'https://www.places4students.com', NULL, NULL, NULL, NULL, '{en}', '{international_student}', true, true),
(gen_random_uuid(), 'housing', 'uOttawa Off-Campus Housing (Places4Students)', 'University of Ottawa official off-campus housing portal connecting students with verified rental listings near campus.', 'https://www.uottawa.ca/current-students/housing', '613-562-5885', '90 University Pvt', 'Ottawa', 'Ontario', '{en,fr}', '{international_student}', true, true),
(gen_random_uuid(), 'housing', 'Carleton University Residence', 'On-campus living options at Carleton University including single rooms, doubles and suite-style residences.', 'https://housing.carleton.ca', '613-520-5609', '1125 Colonel By Dr', 'Ottawa', 'Ontario', '{en}', '{international_student}', false, true),
(gen_random_uuid(), 'housing', 'Ontario Landlord and Tenant Board', 'Tribunal that resolves disputes between landlords and tenants in Ontario, providing information on tenant rights.', 'https://tribunalsontario.ca/ltb/', '1-888-332-3234', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true);

-- Employment (7)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'employment', 'Job Bank Canada', 'Official Government of Canada job search website listing thousands of jobs and labour market information.', 'https://www.jobbank.gc.ca', '1-800-206-7218', NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'employment', 'WorkBC', 'BC provincial employment services offering job search help, training programs and career planning.', 'https://www.workbc.ca', '1-877-952-6914', NULL, 'Vancouver', 'British Columbia', '{en}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'employment', 'uOttawa Co-op and Career Development Centre', 'Co-operative education and career services for University of Ottawa students including job boards and resume help.', 'https://www.uottawa.ca/career-development-centre/', '613-562-5741', '100 Thomas More Pvt', 'Ottawa', 'Ontario', '{en,fr}', '{international_student}', true, true),
(gen_random_uuid(), 'employment', 'Carleton Career Services', 'Career development office at Carleton University offering job postings, resume workshops and employer events.', 'https://carleton.ca/career/', '613-520-6611', '401 Tory Building', 'Ottawa', 'Ontario', '{en}', '{international_student}', true, true),
(gen_random_uuid(), 'employment', 'Hire Immigrants Ottawa', 'Employer engagement initiative connecting Ottawa employers with skilled immigrant talent.', 'https://hireimmigrantsottawa.ca', '613-228-6715', NULL, 'Ottawa', 'Ontario', '{en,fr}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'employment', 'LASI World Skills - Employment Services', 'Employment-focused programs including job search workshops, workplace culture training and mentorship for newcomers.', 'https://www.lasiworldskills.ca/employment', '613-232-3322', '219 Argyle Ave Suite 400', 'Ottawa', 'Ontario', '{en,fr,ar}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'employment', 'Work Permit Conditions - IRCC', 'Official rules for working on or off campus as an international student including the 20-hour per week limit during studies.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work.html', NULL, NULL, NULL, NULL, '{en,fr}', '{international_student}', true, true);

-- Education (6)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'education', 'Language Instruction for Newcomers to Canada (LINC)', 'Free English language classes funded by the federal government for permanent residents and refugees.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/new-life-canada/improve-english-french/classes.html', NULL, NULL, NULL, NULL, '{en,fr}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'education', 'Ottawa-Carleton District School Board', 'Public school board serving Ottawa with English-language schools, ESL programs and adult education.', 'https://www.ocdsb.ca', '613-596-8211', '133 Greenbank Rd', 'Ottawa', 'Ontario', '{en}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'education', 'Algonquin College Language Institute', 'ESL programs and English for Academic Purposes courses for international students and newcomers.', 'https://www.algonquincollege.com/language-institute/', '613-727-4723', '1385 Woodroffe Ave', 'Ottawa', 'Ontario', '{en}', '{international_student,permanent_resident,refugee}', false, true),
(gen_random_uuid(), 'education', 'WES - World Education Services', 'Credential evaluation service recognized across Canada for assessing international education for immigration and employment.', 'https://www.wes.org/ca/', NULL, NULL, 'Toronto', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', false, true),
(gen_random_uuid(), 'education', 'Ottawa Public Library - Newcomer Services', 'Free library card, English and French learning resources, settlement information and computer access for newcomers.', 'https://biblioottawalibrary.ca/en/newcomers', '613-580-2940', '120 Metcalfe St', 'Ottawa', 'Ontario', '{en,fr,ar,zh,so}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'education', 'CanPath Education - Study in Canada', 'Guide for prospective international students covering DLI lists, study permits and choosing Canadian institutions.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html', NULL, NULL, NULL, NULL, '{en,fr}', '{international_student}', true, true);

-- Legal Aid (4)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'legal_aid', 'Legal Aid Ontario', 'Provincial legal aid providing free or low-cost legal assistance for immigration, refugee claims and family law.', 'https://www.legalaid.on.ca', '1-800-668-8258', NULL, NULL, 'Ontario', '{en,fr}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'legal_aid', 'Pro Bono Ontario', 'Free legal advice hotline and clinics for people who cannot afford a lawyer, including immigration matters.', 'https://www.probonoontario.org', '1-855-255-7256', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'legal_aid', 'Community Legal Services Ottawa Centre', 'Free legal services for low-income Ottawa residents covering housing disputes, employment and social benefits.', 'https://www.clsoc.ca', '613-241-7008', '1 Nicholas St Suite 422', 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'legal_aid', 'Immigration and Refugee Board of Canada', 'Independent tribunal making decisions on immigration and refugee matters including refugee claims and appeals.', 'https://irb-cisr.gc.ca', '613-995-6486', NULL, NULL, NULL, '{en,fr}', '{refugee}', true, true);

-- Community (6)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'community', 'Ottawa Chinese Community Service Centre', 'Community centre providing settlement services, language programs and cultural activities for Chinese-speaking newcomers.', 'https://www.occsc.org', '613-235-4875', '381 Kent St Suite 200', 'Ottawa', 'Ontario', '{en,zh}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'community', 'South Asian Community of Ottawa', 'Community association organizing cultural events, festivals and support services for South Asian newcomers.', NULL, NULL, NULL, 'Ottawa', 'Ontario', '{en,hi,ur,pa,ta}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'community', 'Rideau Community Hub', 'Multi-purpose community centre in downtown Ottawa offering recreation, programs and meeting space for newcomers.', 'https://ottawa.ca/en/recreation-and-parks', '613-580-2424', '815 St Laurent Blvd', 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'community', 'Ottawa Newcomer Volunteers Network', 'Volunteer matching service connecting newcomers with volunteer opportunities to gain Canadian experience and build networks.', NULL, NULL, NULL, 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'community', 'Lebanese and Arab Social Services Agency', 'Settlement and social services for Arabic-speaking newcomers in Ottawa including counselling and employment help.', NULL, '613-236-0003', '880 Wellington St W', 'Ottawa', 'Ontario', '{en,fr,ar}', '{permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'community', 'Somali Centre for Family Services', 'Community-based organization supporting Somali and East African newcomers with settlement, employment and youth programs.', 'https://somalicentre.ca', '613-234-6363', '1719 Bank St', 'Ottawa', 'Ontario', '{en,so,ar}', '{permanent_resident,refugee}', true, true);

-- Transport (4)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'transport', 'OC Transpo', 'Ottawa public transit system operating buses and the O-Train LRT with discounted U-Pass for students.', 'https://www.octranspo.com', '613-741-4390', NULL, 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', false, true),
(gen_random_uuid(), 'transport', 'Presto Card', 'Reloadable transit payment card accepted across Ottawa, Toronto and other Ontario transit systems.', 'https://www.prestocard.ca', '1-877-378-6123', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', false, true),
(gen_random_uuid(), 'transport', 'Ontario Driver''s Licence - New Residents', 'Guide for newcomers to Ontario on how to get an Ontario driver''s licence including exchange agreements with other countries.', 'https://www.ontario.ca/page/get-drivers-licence', '1-800-387-3445', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', false, true),
(gen_random_uuid(), 'transport', 'VIA Rail Student Discount', 'Discounted train fares for students traveling between Canadian cities with a valid student ID.', 'https://www.viarail.ca/en/fares-and-packages/rail-passes/student', '1-888-842-7245', NULL, NULL, NULL, '{en,fr}', '{international_student}', false, true);

-- Mental Health (4)
INSERT INTO resources (id, category, title, description, url, phone, address, city, province, language, status_type, free, verified) VALUES
(gen_random_uuid(), 'mental_health', 'BounceBack Ontario', 'Free guided self-help program for adults and youth experiencing mild to moderate depression, anxiety and stress.', 'https://bouncebackontario.ca', '1-866-345-0224', NULL, NULL, 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true),
(gen_random_uuid(), 'mental_health', 'Crisis Services Canada', '24/7 suicide prevention and crisis support service available by phone and text across Canada.', 'https://www.crisisservicescanada.ca', '1-833-456-4566', NULL, NULL, NULL, '{en,fr}', '{international_student,permanent_resident,refugee,visitor}', true, true),
(gen_random_uuid(), 'mental_health', 'Good2Talk - Post-Secondary Student Helpline', 'Free confidential helpline for Ontario post-secondary students for mental health, addictions and well-being support.', 'https://good2talk.ca', '1-866-925-5454', NULL, NULL, 'Ontario', '{en,fr}', '{international_student}', true, true),
(gen_random_uuid(), 'mental_health', 'Canadian Mental Health Association - Ottawa', 'Community mental health programs including counselling, peer support and housing for people experiencing mental illness.', 'https://cmhaottawa.ca', '613-737-7791', '301-311 McArthur Ave', 'Ottawa', 'Ontario', '{en,fr}', '{international_student,permanent_resident,refugee}', true, true);

-- ============================================================
-- JOB LISTINGS (10 rows)
-- ============================================================

INSERT INTO job_listings (id, posted_by, title, company, description, requirements, job_type, salary_range, location, city, remote, status_types, languages_needed, application_url, contact_email, deadline, is_active) VALUES
-- On Campus (3)
(gen_random_uuid(), NULL, 'Library Student Assistant', 'Carleton University Library', 'Assist with circulation desk duties, shelving, and helping patrons locate resources. Flexible hours around class schedule. Training provided.', 'Must be enrolled as a full-time Carleton student. Strong organizational skills and attention to detail.', 'on_campus', '$16.55-$18.00/hr', 'MacOdrum Library, 1125 Colonel By Dr', 'Ottawa', false, '{international_student}', '{en}', 'https://carleton.ca/careers/', 'library@carleton.ca', '2026-04-15', true),
(gen_random_uuid(), NULL, 'IT Help Desk Support', 'University of Ottawa - IT Services', 'Provide technical support to students and staff at campus help desk. Troubleshoot hardware, software and network issues. Rotate evening and weekend shifts.', 'Full-time uOttawa student. Experience with Windows, macOS and basic networking. Bilingual English/French preferred.', 'on_campus', '$17.00-$19.50/hr', '100 Thomas More Pvt', 'Ottawa', false, '{international_student}', '{en,fr}', 'https://uottawa.njoyn.com', 'it-hr@uottawa.ca', '2026-04-01', true),
(gen_random_uuid(), NULL, 'Research Assistant - Data Science Lab', 'Carleton University - School of Computer Science', 'Assist with data collection, cleaning and analysis for NLP research project on multilingual sentiment analysis. Work with Python, pandas and HuggingFace.', 'Graduate or upper-year undergraduate in CS or related field. Experience with Python, data analysis and machine learning fundamentals.', 'on_campus', '$20.00-$24.00/hr', 'Herzberg Building, 1125 Colonel By Dr', 'Ottawa', false, '{international_student}', '{en}', 'https://carleton.ca/scs/', 'research-lab@carleton.ca', '2026-03-28', true),

-- Co-op (3)
(gen_random_uuid(), NULL, 'Software Engineering Intern', 'Shopify', 'Join a product team building tools for millions of merchants. Work on full-stack features using Ruby on Rails and React. Participate in code reviews and ship to production.', 'Enrolled in CS, Software Engineering or related co-op program. Experience with web development frameworks. Strong problem-solving skills.', 'co_op', '$5,000-$6,500/month', '150 Elgin St', 'Ottawa', true, '{international_student}', '{en}', 'https://www.shopify.com/careers/interns', NULL, '2026-05-01', true),
(gen_random_uuid(), NULL, 'Junior Software Developer - Co-op', 'Nokia Ottawa', 'Develop and test features for 5G network management platform. Work with C++ and Python in an agile team. Gain experience with large-scale telecom systems.', 'Co-op student in Computer Engineering, Electrical Engineering or CS. Knowledge of C++ or Python. Understanding of networking concepts is a plus.', 'co_op', '$4,800-$5,800/month', '600 March Rd, Kanata', 'Ottawa', false, '{international_student}', '{en}', 'https://www.nokia.com/careers/', NULL, '2026-04-20', true),
(gen_random_uuid(), NULL, 'Hardware Verification Engineer - Co-op', 'Ciena Corporation', 'Verify optical networking hardware designs using SystemVerilog. Write test benches and work with FPGA prototyping boards alongside senior engineers.', 'Co-op student in Electrical or Computer Engineering. Coursework in digital design and VHDL/Verilog. Strong analytical and debugging skills.', 'co_op', '$4,600-$5,400/month', '385 Terry Fox Dr, Kanata', 'Ottawa', false, '{international_student}', '{en}', 'https://www.ciena.com/about/careers', NULL, '2026-04-10', true),

-- Part Time (2)
(gen_random_uuid(), NULL, 'Team Member', 'Tim Hortons - Rideau Centre', 'Prepare food and beverages, serve customers and maintain store cleanliness. Flexible scheduling with morning, afternoon and evening shifts available.', 'No experience required, training provided. Must be legally authorized to work in Canada. Friendly and reliable.', 'part_time', '$16.55-$17.50/hr', '50 Rideau St', 'Ottawa', false, '{international_student,permanent_resident,refugee}', '{en}', NULL, 'rideau.hiring@timhortons.com', '2026-06-30', true),
(gen_random_uuid(), NULL, 'Cashier / Sales Associate', 'Walmart Supercenter - South Keys', 'Operate cash registers, assist customers and stock shelves. Weekend and evening availability preferred. Employee discount included.', 'Legally authorized to work in Canada. Basic math skills. Ability to stand for extended periods. Customer service orientation.', 'part_time', '$16.55-$17.00/hr', '2210 Bank St', 'Ottawa', false, '{international_student,permanent_resident,refugee}', '{en}', 'https://careers.walmart.ca', NULL, '2026-07-31', true),

-- Internship (2)
(gen_random_uuid(), NULL, 'Policy Research Intern', 'Government of Canada - IRCC', 'Support policy research on immigration settlement outcomes. Analyze data, prepare briefings, and contribute to evidence-based policy recommendations.', 'Enrolled in graduate program in Public Policy, Economics, or Social Sciences. Canadian citizen or permanent resident preferred. Reliability security clearance required.', 'internship', '$22.00-$26.00/hr', '365 Laurier Ave W', 'Ottawa', false, '{permanent_resident}', '{en,fr}', 'https://www.canada.ca/en/public-service-commission/jobs/services/recruitment/students.html', NULL, '2026-04-30', true),
(gen_random_uuid(), NULL, 'Cloud Infrastructure Intern', 'Solace Corporation', 'Help build and maintain cloud infrastructure for event streaming platform. Work with Kubernetes, Terraform and AWS. Remote-first culture.', 'Enrolled in CS, IT or related program. Familiarity with Linux, Docker and cloud platforms. Interest in distributed systems.', 'internship', '$4,500-$5,500/month', '305 Rideau St', 'Ottawa', true, '{international_student}', '{en}', 'https://solace.com/careers/', NULL, '2026-05-15', true);

-- ============================================================
-- HOUSING LISTINGS (8 rows)
-- ============================================================

INSERT INTO housing_listings (id, user_id, title, description, listing_type, price_monthly, bedrooms, bathrooms, address, city, latitude, longitude, available_from, furnished, utilities, pets_allowed, gender_pref, student_only, amenities, languages, is_active) VALUES
(gen_random_uuid(), NULL, 'Furnished Room near uOttawa Campus', 'Bright private room in a 3-bedroom apartment, 5-minute walk to uOttawa campus. Shared kitchen and bathroom. Quiet neighbourhood. Laundry in building. Internet included.', 'room', 750, 1, 1, '275 Laurier Ave E', 'Ottawa', 45.4231, -75.6831, '2026-05-01', true, true, false, NULL, true, '{wifi,laundry,heating,air_conditioning}', '{en,ar}', true),
(gen_random_uuid(), NULL, 'Modern 1-Bedroom Apartment - Sandy Hill', 'Spacious one-bedroom apartment in Sandy Hill, steps from uOttawa. Recently renovated with in-suite laundry, dishwasher and balcony. Secure entry building.', 'apartment', 1650, 1, 1, '180 Osgoode St', 'Ottawa', 45.4245, -75.6780, '2026-06-01', false, false, false, NULL, false, '{laundry,dishwasher,balcony,parking}', '{en,fr}', true),
(gen_random_uuid(), NULL, 'Affordable Basement Suite near Carleton', 'Clean basement apartment with separate entrance near Carleton campus. Includes bedroom, living area, kitchenette and full bathroom. Bus stop steps away.', 'basement', 900, 1, 1, '1580 Prince of Wales Dr', 'Ottawa', 45.3812, -75.6970, '2026-05-01', true, true, false, NULL, true, '{wifi,heating,separate_entrance}', '{en}', true),
(gen_random_uuid(), NULL, 'Homestay with Canadian Family - Barrhaven', 'Welcoming Canadian family offering homestay for international students. Private room with meals included (breakfast and dinner). Practice English in a home environment.', 'homestay', 1100, 1, 1, '89 Berrigan Dr', 'Ottawa', 45.3260, -75.7360, '2026-04-15', true, true, false, NULL, true, '{wifi,meals_included,heating,parking}', '{en}', true),
(gen_random_uuid(), NULL, 'Shared 2-Bedroom Apartment - Centretown', 'Looking for a roommate to share a 2-bedroom apartment in Centretown. Walking distance to Parliament, Rideau Centre and both universities. Great nightlife nearby.', 'room', 825, 1, 1, '440 Kent St', 'Ottawa', 45.4166, -75.7003, '2026-05-15', false, true, false, NULL, false, '{wifi,laundry,gym,heating}', '{en,zh}', true),
(gen_random_uuid(), NULL, 'Large 2-Bedroom Apartment - Heron Gate', 'Spacious two-bedroom apartment in diverse Heron Gate neighbourhood. Close to bus routes, Billings Bridge Mall and grocery stores. Great for families or roommates.', 'apartment', 1450, 2, 1, '1455 Heron Rd', 'Ottawa', 45.3870, -75.6600, '2026-06-01', false, true, true, NULL, false, '{laundry,parking,balcony,storage}', '{en,ar,so}', true),
(gen_random_uuid(), NULL, 'Studio Apartment - Byward Market', 'Cozy studio in the heart of the Byward Market. Perfect for a single student. Walking distance to uOttawa, restaurants and shops. Heritage building with character.', 'apartment', 1350, 0, 1, '55 Clarence St', 'Ottawa', 45.4290, -75.6920, '2026-05-01', true, true, false, NULL, false, '{wifi,heating,air_conditioning}', '{en,fr}', true),
(gen_random_uuid(), NULL, 'Room in Townhouse near Algonquin College', 'Private room available in a 4-bedroom townhouse shared with other students. Common areas are clean and well-maintained. Close to Algonquin College and bus routes.', 'room', 600, 1, 1, '1245 Baseline Rd', 'Ottawa', 45.3520, -75.7560, '2026-04-01', true, true, false, NULL, true, '{wifi,laundry,heating,parking}', '{en,hi}', true);

-- ============================================================
-- FORUM POSTS (5 rows)
-- ============================================================

INSERT INTO forum_posts (id, user_id, title, content, category, tags, city, upvotes, reply_count, pinned, language) VALUES
(gen_random_uuid(), NULL, 'How do I get my SIN number in Ottawa?', 'I just arrived in Ottawa as an international student. I need a Social Insurance Number to start working on campus. Can anyone explain the process? Do I need to go in person or can I apply online? What documents should I bring? Thanks in advance!', 'immigration', '{sin,documents,work_permit,newcomer}', 'Ottawa', 24, 0, false, 'en'),
(gen_random_uuid(), NULL, 'Best bank accounts for international students?', 'Hi everyone, I am trying to choose a bank for my first Canadian account. I have heard that some banks offer free accounts for newcomers. Which bank has the best deal for international students? I care about no monthly fees, a good app and being able to send money home easily.', 'banking', '{banking,student_account,newcomer,money_transfer}', 'Ottawa', 31, 0, false, 'en'),
(gen_random_uuid(), NULL, 'Looking for halal food in Ottawa', 'Salam everyone! I just moved to Ottawa for school and I am looking for good halal restaurants and grocery stores. Anywhere near uOttawa or downtown would be great. Also, are there any halal meal prep services? Would love your recommendations!', 'community', '{halal,food,restaurants,groceries,muslim}', 'Ottawa', 18, 0, false, 'en'),
(gen_random_uuid(), NULL, 'How to prepare for Canadian winter?', 'This will be my first winter in Canada and I am from a tropical country. I have no idea what to expect! What kind of clothes do I need? How cold does it actually get in Ottawa? Any tips for surviving the winter months? I heard it can go below -30C which sounds terrifying.', 'general', '{winter,clothing,weather,tips,newcomer}', 'Ottawa', 42, 0, false, 'en'),
(gen_random_uuid(), NULL, 'Part-time job tips while studying?', 'I am an international student allowed to work 20 hours per week off campus. What are the best part-time jobs for students in Ottawa? I have experience in retail but I am open to anything. How do I balance work and a full course load? Any advice appreciated.', 'jobs', '{part_time,work_permit,student_jobs,employment}', 'Ottawa', 27, 0, false, 'en');

-- ============================================================
-- KNOWLEDGE BASE (20 rows) — embeddings set to NULL
-- ============================================================

INSERT INTO knowledge_base (id, title, content, source_url, source_name, category, province, status_type, language, embedding) VALUES
(gen_random_uuid(), 'How to Apply for a Social Insurance Number (SIN)',
'A Social Insurance Number (SIN) is required to work in Canada or access government programs. International students can apply in person at a Service Canada office. Required documents: valid passport, study permit, and a letter of acceptance from your designated learning institution (DLI). Processing is usually immediate if you visit in person. You can also apply by mail. Your SIN starting with 9 is temporary and tied to your work authorization. In Ottawa, the nearest Service Canada office is at 110 Laurier Ave W.',
'https://www.canada.ca/en/employment-social-development/services/sin/apply.html', 'Government of Canada', 'immigration', 'Ontario', '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'OHIP Enrollment and 3-Month Waiting Period',
'Ontario Health Insurance Plan (OHIP) covers most medical services for eligible residents. New permanent residents and refugees must complete a 3-month waiting period before coverage begins. During this waiting period, you should obtain private health insurance (such as UHIP for university students). To apply, visit a ServiceOntario office with proof of identity, Ontario residency and immigration status. International students on study permits are generally NOT eligible for OHIP and must use UHIP or equivalent university insurance.',
'https://www.ontario.ca/page/apply-ohip-and-get-health-card', 'Government of Ontario', 'health', 'Ontario', '{permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Study Permit Work Rules: 20 Hours Per Week',
'International students with a valid study permit can work up to 20 hours per week during regular academic sessions and full-time during scheduled breaks (such as winter and summer holidays). You must be enrolled full-time at a designated learning institution (DLI) and have a valid study permit that says you are allowed to work off campus. No separate work permit is needed. On-campus work has no hour limit. Violating the 20-hour rule can result in loss of student status and deportation.',
'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work.html', 'IRCC', 'employment', NULL, '{international_student}', 'en', NULL),

(gen_random_uuid(), 'Filing Taxes as a Newcomer in Canada',
'All residents of Canada, including international students and newcomers, may need to file a tax return. Even if you earned no income, filing a return can qualify you for benefits like the GST/HST credit and Canada Child Benefit. The tax year runs January to December and returns are due by April 30. Use a free tax clinic (such as those offered by community organizations through the CVITP program) or free software like Wealthsimple Tax. You will need your SIN and any T4 slips from employers.',
'https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/personal-income/newcomers-canada-immigrants.html', 'Canada Revenue Agency', 'immigration', NULL, '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'GST/HST Credit for Newcomers',
'The GST/HST credit is a tax-free quarterly payment to help individuals and families with low or modest income offset the GST/HST they pay. Newcomers, including international students who file a tax return, may be eligible. To apply, file your income tax return and complete Form RC151 (GST/HST Credit Application for Individuals Who Become Residents of Canada). Payments are issued quarterly in January, April, July and October. For a single person, the maximum annual credit is approximately $496.',
'https://www.canada.ca/en/revenue-agency/services/child-family-benefits/gsthstc-eligibility.html', 'Canada Revenue Agency', 'banking', NULL, '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Post-Graduation Work Permit (PGWP) Eligibility',
'After graduating from a designated learning institution (DLI) in Canada, international students may apply for a Post-Graduation Work Permit (PGWP). The PGWP allows you to work for any employer in Canada. The length of the permit depends on your program length: programs of 8 months to 2 years receive a PGWP equal to program length; programs of 2+ years receive a 3-year PGWP. You must apply within 180 days of receiving written confirmation of program completion. You must have maintained full-time student status.',
'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/work/after-graduation/eligibility.html', 'IRCC', 'immigration', NULL, '{international_student}', 'en', NULL),

(gen_random_uuid(), 'Getting an Ontario Driver''s Licence',
'New Ontario residents must get an Ontario driver''s licence within 60 days. Ontario uses a graduated licensing system (G1 -> G2 -> G). If you have a valid licence from certain countries (USA, UK, Australia, Japan, South Korea, etc.), you may exchange it directly without testing. Others must start with a G1 written test ($159.75 fee). The G1 test covers road signs and rules. After passing, you must wait 12 months (or 8 months with an approved driving course) before taking the G2 road test.',
'https://www.ontario.ca/page/get-drivers-licence', 'Government of Ontario', 'transport', 'Ontario', '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Opening a Bank Account as a Newcomer',
'You can open a bank account in Canada even before arriving. Major banks (TD, RBC, Scotiabank, BMO, CIBC) all offer newcomer packages with no monthly fees for the first year and credit cards requiring no Canadian credit history. To open an account you need: two pieces of ID (passport and study/work permit), proof of address (can be temporary), and your SIN (optional at account opening but needed for interest reporting). Most banks have branches near university campuses.',
'https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html', 'Financial Consumer Agency of Canada', 'banking', NULL, '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Healthcare Without OHIP: Options for International Students',
'International students in Ontario are not eligible for OHIP and must have private health insurance. Ontario universities require enrollment in the University Health Insurance Plan (UHIP) which costs approximately $756 per year. UHIP covers doctor visits, hospital stays, emergency care, mental health services and prescription drugs. For additional coverage (dental, vision, extended prescriptions), check your student union supplementary insurance plan. Walk-in clinics accept UHIP but always carry your UHIP card.',
'https://uhip.ca/Enrollment/Coverage', 'UHIP', 'health', 'Ontario', '{international_student}', 'en', NULL),

(gen_random_uuid(), 'Express Entry: Overview for Skilled Workers',
'Express Entry is Canada''s main pathway for skilled workers to become permanent residents. It manages three immigration programs: Federal Skilled Worker, Federal Skilled Trades, and Canadian Experience Class. Candidates create an online profile and are ranked using the Comprehensive Ranking System (CRS). Top-ranked candidates receive Invitations to Apply (ITAs) in regular draws. Key factors: age, education, language scores (IELTS/CELPIP/TEF), work experience, and Canadian connections. Processing time is approximately 6 months.',
'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', 'IRCC', 'immigration', NULL, '{international_student,permanent_resident}', 'en', NULL),

(gen_random_uuid(), 'Renting in Ontario: Know Your Rights',
'The Residential Tenancies Act (RTA) protects tenants in Ontario. Key rights: landlords cannot increase rent more than the annual guideline (2.5% for 2024); landlords must provide 24 hours written notice before entering; security deposits beyond last month''s rent are illegal; landlords cannot refuse tenants based on immigration status. If you have a dispute, contact the Landlord and Tenant Board (LTB). Always get a written lease (Ontario has a standard lease form). Never pay cash without a receipt.',
'https://www.ontario.ca/page/renting-ontario-your-rights', 'Government of Ontario', 'housing', 'Ontario', '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Getting a Canadian Cell Phone Plan',
'Major carriers include Rogers, Bell and Telus with extensive coverage. For budget options, consider their sub-brands: Fido, Virgin Plus, Koodo and Public Mobile. Prepaid plans start around $25/month. You need a Canadian bank account or credit card for postpaid plans. Bring-your-own-device (BYOD) plans save money. Ensure your phone supports Canadian LTE bands. Port your number if switching carriers. Freedom Mobile and Videotron offer competitive plans in certain cities.',
NULL, 'MaplePath Knowledge', 'community', NULL, '{international_student,permanent_resident,refugee,visitor}', 'en', NULL),

(gen_random_uuid(), 'Navigating Ottawa by Public Transit',
'OC Transpo is Ottawa''s public transit system. University students get a U-Pass included in tuition providing unlimited travel. Use a Presto card for pay-per-ride ($3.70 per ride). The Confederation Line (O-Train Line 1) runs east-west through downtown connecting Tunney''s Pasture to Blair. The Trillium Line (Line 2) runs north-south. Google Maps and the OC Transpo app provide real-time trip planning. Night service (routes 90-99) runs on weekends.',
'https://www.octranspo.com', 'OC Transpo', 'transport', 'Ontario', '{international_student,permanent_resident,refugee,visitor}', 'en', NULL),

(gen_random_uuid(), 'Canadian Workplace Culture for Newcomers',
'Canadian workplaces tend to value punctuality, direct but polite communication, and teamwork. Arrive on time or a few minutes early. Address colleagues by first name unless told otherwise. Two weeks notice is standard when leaving a job. Minimum wage in Ontario is $16.55/hour. You are entitled to breaks, overtime pay and a safe workplace. If you face workplace discrimination or harassment, contact the Ontario Human Rights Commission or your university''s equity office.',
NULL, 'MaplePath Knowledge', 'employment', 'Ontario', '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Building Canadian Credit History',
'Building credit is essential for renting apartments, getting loans, and more. Start with a secured credit card from your bank or a student credit card. Use it for small purchases and pay the full balance every month. After 6 months of responsible use, your credit score will start building. Check your score free through Borrowell or Credit Karma. Avoid carrying a balance, making late payments, or applying for too many cards at once. A good credit score in Canada is 650 and above.',
NULL, 'MaplePath Knowledge', 'banking', NULL, '{international_student,permanent_resident,refugee}', 'en', NULL),

(gen_random_uuid(), 'Emergency Numbers and Services in Canada',
'Call 911 for police, fire or medical emergencies. For non-emergency police matters, call your local police non-emergency line (Ottawa: 613-236-1222). Telehealth Ontario (1-866-797-0000) provides 24/7 free health advice by phone. For mental health crises, call the Crisis Line at 1-833-456-4566 (24/7). For poison control, call 1-800-268-9017. In case of severe weather, check Environment Canada weather warnings. Keep your address memorized or written down in case of emergency.',
NULL, 'MaplePath Knowledge', 'health', 'Ontario', '{international_student,permanent_resident,refugee,visitor}', 'en', NULL),

(gen_random_uuid(), 'Winter Survival Guide for Newcomers',
'Ottawa winters are cold with temperatures dropping to -25C or below with wind chill. Essential gear: insulated winter jacket, thermal base layers, waterproof winter boots with good traction, warm hat covering ears, insulated gloves, and a scarf. Layer your clothing. Black ice is a major hazard on sidewalks. Keep an emergency kit in your car if driving. The heating bill increases in winter so budget accordingly. Indoor humidity drops significantly so consider a humidifier. Winter tires are strongly recommended.',
NULL, 'MaplePath Knowledge', 'community', 'Ontario', '{international_student,permanent_resident,refugee,visitor}', 'en', NULL),

(gen_random_uuid(), 'Canadian Phone and Internet Scams to Avoid',
'Common scams targeting newcomers: CRA scam calls threatening arrest for unpaid taxes (CRA never calls to threaten); immigration scam calls claiming your SIN is compromised; fake job offers asking for upfront fees; rental scams for apartments that do not exist. Never give personal information over unsolicited calls. The CRA will never ask for payment via gift cards or cryptocurrency. Report scams to the Canadian Anti-Fraud Centre at 1-888-495-8501. If unsure, hang up and call the organization directly.',
'https://www.antifraudcentre-centreantifraude.ca', 'Canadian Anti-Fraud Centre', 'community', NULL, '{international_student,permanent_resident,refugee,visitor}', 'en', NULL),

(gen_random_uuid(), 'Study Permit Extension Process',
'You should apply to extend your study permit at least 30 days before it expires (recommended 90 days ahead). Apply online through your IRCC account. Required: valid passport, letter of enrollment from DLI, proof of financial support, and digital photos. Processing time varies (typically 60-120 days). If you apply before your permit expires, you can stay in Canada on implied status until a decision is made. If your permit expires without extension, you may lose your student status and work authorization.',
'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/extend-study-permit.html', 'IRCC', 'immigration', NULL, '{international_student}', 'en', NULL),

(gen_random_uuid(), 'Free English and French Language Classes',
'LINC (Language Instruction for Newcomers to Canada) provides free English classes for permanent residents and refugees. Classes range from beginner (CLB 1) to advanced (CLB 8). Some programs include free childcare and transportation allowances. In Ottawa, LINC is offered at OCISO, Catholic Centre for Immigrants, and Algonquin College. For French, look for CLIC (Cours de Langue pour les Immigrants au Canada). International students can access ESL classes through their university or community colleges for a fee.',
'https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/new-life-canada/improve-english-french/classes.html', 'IRCC', 'education', 'Ontario', '{permanent_resident,refugee}', 'en', NULL);

-- ============================================================
-- MAP PINS (15 rows) — Ottawa landmarks
-- ============================================================

INSERT INTO map_pins (id, user_id, title, category, description, address, latitude, longitude, city, languages, website, phone, hours, verified, upvotes) VALUES
-- Worship / Cultural Centres
(gen_random_uuid(), NULL, 'Ottawa Mosque (Masjid Bilal)', 'worship', 'One of the largest mosques in Ottawa offering daily prayers, Friday Jummah, and community events. Newcomer welcome programs available.', '111 Blackburn Ave', 45.4230, -75.6780, 'Ottawa', '{en,ar}', 'https://ottawamosque.ca', '613-232-2510', 'Daily 5am-10pm, Friday Jummah 1:00pm', true, 12),
(gen_random_uuid(), NULL, 'Hindu Temple of Ottawa-Carleton', 'worship', 'Hindu temple serving the Ottawa community with regular puja services, cultural events, and vegetarian langar meals.', '4835 Bank St', 45.3060, -75.6360, 'Ottawa', '{en,hi,ta}', 'https://hindutemplottawa.ca', '613-822-2811', 'Daily 8am-12pm, 5pm-9pm', true, 8),
(gen_random_uuid(), NULL, 'Gurdwara Sahib Ottawa (Sikh Temple)', 'worship', 'Sikh Gurdwara offering daily services, free community langar (meal) and Punjabi language classes. Everyone welcome regardless of faith.', '979 Woodward Dr', 45.3510, -75.7190, 'Ottawa', '{en,pa}', NULL, '613-224-3462', 'Daily 5am-9pm, Langar 12pm-2pm', true, 10),

-- Food
(gen_random_uuid(), NULL, 'Shawarma Palace', 'food', 'Popular halal restaurant chain known for large portions and affordable prices. Multiple locations across Ottawa. Student favourite.', '464 Rideau St', 45.4310, -75.6820, 'Ottawa', '{en,ar}', 'https://shawarmapalace.ca', '613-789-4011', 'Mon-Sun 11am-12am', true, 22),
(gen_random_uuid(), NULL, 'Istanbul Kebab House', 'food', 'Authentic Turkish and Middle Eastern cuisine with halal options. Cozy atmosphere near uOttawa campus.', '75 Laurier Ave E', 45.4240, -75.6850, 'Ottawa', '{en,tr,ar}', NULL, '613-241-7272', 'Mon-Sun 11am-10pm', true, 15),

-- Banking
(gen_random_uuid(), NULL, 'TD Bank - uOttawa Branch', 'banking', 'TD branch near University of Ottawa campus with newcomer banking specialists and multilingual staff.', '100 Rideau St', 45.4280, -75.6910, 'Ottawa', '{en,fr,zh,ar}', 'https://www.td.com', '613-244-5775', 'Mon-Fri 8am-6pm, Sat 9am-3pm', true, 6),
(gen_random_uuid(), NULL, 'RBC Royal Bank - Carleton Campus', 'banking', 'RBC branch inside Carleton University campus serving students with newcomer account packages.', '1125 Colonel By Dr, University Centre', 45.3830, -75.6960, 'Ottawa', '{en,fr}', 'https://www.rbc.com', '613-564-7452', 'Mon-Fri 9:30am-5pm', true, 5),

-- Health
(gen_random_uuid(), NULL, 'Appletree Medical Group - Rideau', 'health', 'Walk-in medical clinic accepting patients with OHIP, UHIP and private insurance. No appointment needed.', '130 Slater St', 45.4200, -75.6960, 'Ottawa', '{en,fr}', 'https://www.appletreemedicalgroup.com', '613-225-8733', 'Mon-Fri 8am-8pm, Sat-Sun 10am-4pm', true, 9),
(gen_random_uuid(), NULL, 'University of Ottawa Health Services', 'health', 'Primary care clinic for uOttawa students covering general health, mental health, sexual health and immunizations.', '100 Marie Curie, Room 213', 45.4225, -75.6835, 'Ottawa', '{en,fr}', 'https://www.uottawa.ca/wellness/health-services', '613-564-3950', 'Mon-Fri 8:30am-4:30pm', true, 11),

-- Community Centres
(gen_random_uuid(), NULL, 'Rideau Community Hub', 'community', 'Multi-purpose community centre with recreation programs, meeting rooms and newcomer support services. Free Wi-Fi.', '815 St Laurent Blvd', 45.4300, -75.6670, 'Ottawa', '{en,fr}', 'https://ottawa.ca/en/recreation-and-parks', '613-580-2424', 'Mon-Fri 8am-9pm, Sat 9am-5pm', true, 7),
(gen_random_uuid(), NULL, 'Canterbury Community Centre', 'community', 'Community centre in south Ottawa near Carleton campus with gym, pool and youth programs. Affordable recreation passes.', '2185 Arch St', 45.3780, -75.6870, 'Ottawa', '{en,fr}', 'https://ottawa.ca/en/recreation-and-parks', '613-580-2424', 'Mon-Fri 6am-10pm, Sat-Sun 7am-6pm', true, 5),

-- Education
(gen_random_uuid(), NULL, 'Ottawa Public Library - Main Branch', 'education', 'Central library branch with free Wi-Fi, computer access, language learning resources and newcomer settlement information.', '120 Metcalfe St', 45.4210, -75.6940, 'Ottawa', '{en,fr}', 'https://biblioottawalibrary.ca', '613-580-2940', 'Mon-Thu 10am-9pm, Fri-Sat 10am-6pm, Sun 1pm-5pm', true, 14),

-- Transport
(gen_random_uuid(), NULL, 'OC Transpo Rideau Station', 'transport', 'Major O-Train Line 1 station in downtown Ottawa connecting to multiple bus routes. Presto card reload available.', '95 Rideau St (underground)', 45.4260, -75.6920, 'Ottawa', '{en,fr}', 'https://www.octranspo.com', '613-741-4390', '5:30am-1:00am daily', true, 16),

-- Housing
(gen_random_uuid(), NULL, 'Service Canada Centre - Ottawa', 'other', 'Government services centre for SIN applications, EI claims and passport services. Bring valid ID and immigration documents.', '110 Laurier Ave W', 45.4220, -75.6980, 'Ottawa', '{en,fr}', 'https://www.canada.ca/en/employment-social-development/corporate/portfolio/service-canada.html', '1-800-622-6232', 'Mon-Fri 8:30am-4:00pm', true, 19),

(gen_random_uuid(), NULL, 'International Student Services - uOttawa', 'education', 'Support office for international students at uOttawa providing immigration advising, orientation and cultural programming.', '90 University Pvt, Jock Turcot Building', 45.4235, -75.6836, 'Ottawa', '{en,fr}', 'https://www.uottawa.ca/international/', '613-562-5847', 'Mon-Fri 9am-4:30pm', true, 13);
